In [2]:
import numpy as np
import pandas as pd
import requests

In [3]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=6ef6a75eb8d77bff00563bc0ce73c51d&language=en-US&page=1')

In [4]:
pd.DataFrame(response.json()['results'])[['title', 'id', 'genre_ids', 'overview']]

,title,id,genre_ids,overview
0,The Shawshank Redemption,278,"[18, 80]",Imprisoned in the 1940s for the double murder ...
1,The Godfather,238,"[18, 80]","Spanning the years 1945 to 1955, a chronicle o..."
2,KPop Demon Hunters,803796,"[16, 14, 28, 35, 10402]","When K-pop superstars Rumi, Mira and Zoey aren..."
3,The Godfather Part II,240,"[18, 80]",In the continuing saga of the Corleone crime f...
4,Schindler's List,424,"[18, 36, 10752]",The true story of how businessman Oskar Schind...
5,12 Angry Men,389,[18],The defense and the prosecution have rested an...
6,Spirited Away,129,"[16, 10751, 14]","A young girl, Chihiro, becomes trapped in a st..."
7,The Dark Knight,155,"[18, 28, 80, 53]",Batman raises the stakes in his war on crime. ...
8,Dilwale Dulhania Le Jayenge,19404,"[35, 18, 10749]","Raj is a rich, carefree, happy-go-lucky second..."
9,The Green Mile,497,"[14, 18, 80]",A supernatural tale set on death row in a Sout...
10,Parasite,496243,"[35, 53, 18]","All unemployed, Ki-taek's family takes peculia..."
11,Pulp Fiction,680,"[53, 80, 35]","A burger-loving hit man, his philosophical par..."
12,The Lord of the Rings: The Return of the King,122,"[12, 14, 28]",As armies mass for a final battle that will de...
13,Your Name.,372058,"[16, 10749, 18]",High schoolers Mitsuha and Taki are complete s...
14,Forrest Gump,13,"[35, 18, 10749]",A man with a low IQ has accomplished great thi...
15,"The Good, the Bad and the Ugly",429,[37],While the Civil War rages on between the Union...
16,Interstellar,157336,"[12, 18, 878]",The adventures of a group of explorers who mak...
17,GoodFellas,769,"[18, 80]","The true story of Henry Hill, a half-Irish, ha..."
18,Seven Samurai,346,"[28, 18]",A samurai answers a village's request for prot...
19,Grave of the Fireflies,12477,"[16, 18, 10752]","In the final months of World War II, 14-year-o..."

In [5]:
df = pd.DataFrame()

In [6]:
for i in range(1,512):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=6ef6a75eb8d77bff00563bc0ce73c51d&language=en-US&page={}'.format(i))
    if response.status_code == 200 and 'results' in response.json():
        temp_df = pd.DataFrame(response.json()['results'])[['title', 'id', 'genre_ids', 'overview']]
        df = pd.concat([df, temp_df], ignore_index=True)
    else:
        print(f"Skipping page {i}: {response.status_code}")

Skipping page 501: 400
Skipping page 502: 400
Skipping page 503: 400
Skipping page 504: 400
Skipping page 505: 400
Skipping page 506: 400
Skipping page 507: 400
Skipping page 508: 400
Skipping page 509: 400
Skipping page 510: 400
Skipping page 511: 400

In [18]:
df.shape

(10000, 3)

In [8]:
df.head()

,title,id,genre_ids,overview
0,The Shawshank Redemption,278,"[18, 80]",Imprisoned in the 1940s for the double murder ...
1,The Godfather,238,"[18, 80]","Spanning the years 1945 to 1955, a chronicle o..."
2,KPop Demon Hunters,803796,"[16, 14, 28, 35, 10402]","When K-pop superstars Rumi, Mira and Zoey aren..."
3,The Godfather Part II,240,"[18, 80]",In the continuing saga of the Corleone crime f...
4,Schindler's List,424,"[18, 36, 10752]",The true story of how businessman Oskar Schind...

In [9]:
response = requests.get('https://api.themoviedb.org/3/genre/movie/list?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US')
genres = (response.json()['genres'])

In [10]:
genres

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 80, 'name': 'Crime'},
 {'id': 99, 'name': 'Documentary'},
 {'id': 18, 'name': 'Drama'},
 {'id': 10751, 'name': 'Family'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 36, 'name': 'History'},
 {'id': 27, 'name': 'Horror'},
 {'id': 10402, 'name': 'Music'},
 {'id': 9648, 'name': 'Mystery'},
 {'id': 10749, 'name': 'Romance'},
 {'id': 878, 'name': 'Science Fiction'},
 {'id': 10770, 'name': 'TV Movie'},
 {'id': 53, 'name': 'Thriller'},
 {'id': 10752, 'name': 'War'},
 {'id': 37, 'name': 'Western'}]

In [11]:
def get_genre_string(genre_ids_list, genres):
    if not genre_ids_list:
        return "No genres"

    # Create a mapping from id to name
    genre_dict = {g['id']: g['name'] for g in genres}

    # Collect names for the given genre_ids
    genre_names = [genre_dict.get(gid) for gid in genre_ids_list if gid in genre_dict]

    # Return comma-separated string
    return ', '.join(genre_names) if genre_names else "No genres"

In [12]:
df['genre'] = df['genre_ids'].apply(lambda x: get_genre_string(x, genres))
df.head()

,title,id,genre_ids,overview,genre
0,The Shawshank Redemption,278,"[18, 80]",Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
1,The Godfather,238,"[18, 80]","Spanning the years 1945 to 1955, a chronicle o...","Drama, Crime"
2,KPop Demon Hunters,803796,"[16, 14, 28, 35, 10402]","When K-pop superstars Rumi, Mira and Zoey aren...","Animation, Fantasy, Action, Comedy, Music"
3,The Godfather Part II,240,"[18, 80]",In the continuing saga of the Corleone crime f...,"Drama, Crime"
4,Schindler's List,424,"[18, 36, 10752]",The true story of how businessman Oskar Schind...,"Drama, History, War"

In [13]:
df.isnull().sum()

title        0
id           0
genre_ids    0
overview     0
genre        0
dtype: int64

In [14]:
df.drop('genre_ids', axis=1, inplace=True)
df.head()

,title,id,overview,genre
0,The Shawshank Redemption,278,Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
1,The Godfather,238,"Spanning the years 1945 to 1955, a chronicle o...","Drama, Crime"
2,KPop Demon Hunters,803796,"When K-pop superstars Rumi, Mira and Zoey aren...","Animation, Fantasy, Action, Comedy, Music"
3,The Godfather Part II,240,In the continuing saga of the Corleone crime f...,"Drama, Crime"
4,Schindler's List,424,The true story of how businessman Oskar Schind...,"Drama, History, War"

In [15]:
df.drop('id', axis=1, inplace=True)
df.head()

,title,overview,genre
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama, Crime"
2,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...","Animation, Fantasy, Action, Comedy, Music"
3,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama, Crime"
4,Schindler's List,The true story of how businessman Oskar Schind...,"Drama, History, War"

In [19]:
df.to_csv("movies.csv")

# **`Text Preprocessing`**

*`Lower Casing`*

In [16]:
df["overview"] = df['overview'].str.lower()
df['overview'].head()

0    imprisoned in the 1940s for the double murder ...
1    spanning the years 1945 to 1955, a chronicle o...
2    when k-pop superstars rumi, mira and zoey aren...
3    in the continuing saga of the corleone crime f...
4    the true story of how businessman oskar schind...
Name: overview, dtype: object

`HTML tags removal`

In [17]:
import re
df['overview'].str.contains('<.*?>').sum()

np.int64(0)